'''
C DMG Gameboy Emulator Project - MorganPG

gen_boilerplate.py

A boilerplate generator that autogenerates a C switch case statement from an opcodes.json file (https://gbdev.io/gb-opcodes/Opcodes.json)
Inspiration will be heavily taken from https://github.com/MorganPG1/py-dmg-emu/blob/main/gen_boilerplate.py
'''

import json
import datetime

#i should probably replicate a similar template format in py-dmg-emu because damn this is clean af
TEMPLATE = """\
/*
 * C DMG Gameboy Emulator Project - MorganPG
 * 
 * boilerplate.c
 * 
 * An autogenerated boilerplate generated by gen_boilerplate.py at {datetime_str}
 * Do not edit this file manually, edit the generator
*/

#include <stdint.h>
#include "gb.h"
#include "cpu.h"

void execute_instr(dmg_gameboy_t *gb, uint8_t opcode) {{
    uint8_t cycles[] = {{0,0}};
    switch (opcode) {{
{main_block}
    }}
}}
"""

datetime_string = datetime.datetime.now().strftime("%d/%m/%y %H:%M:%S")

with open("opcodes.json") as f:
    data = json.load(f)["unprefixed"] #only load unprefixed instructions because the prefixed ones follow the same decoding layout for all of them

main_block = ""
for opcode, instr in data.items():
    opcode_int = int(opcode, 16)

    instr_str = instr["mnemonic"]
    operands = instr["operands"]
    cycles = instr["cycles"]

    is_illegal = "ILLEGAL" in instr_str

    for i, operand in enumerate(operands):
        imm = operand["immediate"]
        inc = operand["increment"] if "increment" in operand else False
        dec = operand["decrement"] if "decrement" in operand else False

        name = operand["name"]
        name += "+" if inc else ""
        name += "-" if dec else ""

        operand_str = ", " if i > 0 else " "
        operand_str = f"{operand_str}{name}" if imm else f"{operand_str}[{name}]"

        instr_str += operand_str


    main_block += f"        case {opcode}: // {instr_str}\n"
    for i,c in enumerate(cycles):
        main_block += f"            cycles[{i}] = {c-4};\n"

    if (opcode_int) == 0:
        pass
    elif (opcode_int & 0b11001111) == 1:
        main_block += f"            handle_ld_r16_imm16(gb, opcode);\n"
    elif (opcode_int & 0b11001111) == 2:
        main_block += f"            handle_ld_r16mem_a(gb, opcode);\n"
    elif (opcode_int & 0b11001111) == 10:
        main_block += f"            handle_ld_a_r16mem(gb, opcode);\n"
    main_block += f"            break;\n"

outs = TEMPLATE.format(datetime_str=datetime_string, main_block=main_block)

with open("boilerplate.c", "w") as outf:
    outf.write(outs)