'''
C DMG Gameboy Emulator Project - MorganPG

gen_boilerplate.py

A boilerplate generator that autogenerates a C switch case statement from an opcodes.json file (https://gbdev.io/gb-opcodes/Opcodes.json)
Inspiration will be heavily taken from https://github.com/MorganPG1/py-dmg-emu/blob/main/gen_boilerplate.py
'''

import json
import datetime

#i should probably replicate a similar template format in py-dmg-emu because damn this is clean af
TEMPLATE = """\
/*
 * C DMG Gameboy Emulator Project - MorganPG
 * 
 * core/boilerplate.c
 * 
 * An autogenerated boilerplate generated by gen_boilerplate.py at {datetime_str}
 * Do not edit this file manually, edit the generator
*/

#include <stdint.h>
#include <stdio.h>
#include "gb.h"
#include "cpu.h"

void execute_instr(dmg_gameboy_t *gb, uint8_t opcode) {{
    uint8_t cycles[] = {{0,0}};
    switch (opcode) {{
{main_block}
    }}
}}
"""

datetime_string = datetime.datetime.now().strftime("%d/%m/%y %H:%M:%S")

with open("opcodes.json") as f:
    data = json.load(f)["unprefixed"] #only load unprefixed instructions because the prefixed ones follow the same decoding layout for all of them

main_block = ""
for opcode, instr in data.items():
    opcode_int = int(opcode, 16)

    instr_str = instr["mnemonic"]
    operands = instr["operands"]
    cycles = instr["cycles"]

    is_illegal = "ILLEGAL" in instr_str

    for i, operand in enumerate(operands):
        imm = operand["immediate"]
        inc = operand["increment"] if "increment" in operand else False
        dec = operand["decrement"] if "decrement" in operand else False

        name = operand["name"]
        name += "+" if inc else ""
        name += "-" if dec else ""

        operand_str = ", " if i > 0 else " "
        operand_str = f"{operand_str}{name}" if imm else f"{operand_str}[{name}]"

        instr_str += operand_str


    main_block += f"        case {opcode}: // {instr_str}\n"
    for i,c in enumerate(cycles):
        main_block += f"            cycles[{i}] = {c-4};\n"

    if (opcode_int) == 0:
        pass
    elif is_illegal:
        main_block += f'            printf("Invalid opcode %02X", opcode);\n'
        main_block += f"            gb->running = false;\n"
    elif (opcode_int & 0b11001111) == 1:
        main_block += f"            handle_ld_r16_imm16(gb, opcode, cycles);\n"
    elif (opcode_int & 0b11001111) == 2:
        main_block += f"            handle_ld_r16mem_a(gb, opcode, cycles);\n"
    elif (opcode_int & 0b11001111) == 10:
        main_block += f"            handle_ld_a_r16mem(gb, opcode, cycles);\n"
    elif (opcode_int) == 8:
        main_block += f"            handle_ld_imm16_sp(gb, opcode, cycles);\n"
    elif (opcode_int & 0b11001111) == 3:
        main_block += f"            handle_inc_r16(gb, opcode, cycles);\n"
    elif (opcode_int & 0b11001111) == 11:
        main_block += f"            handle_dec_r16(gb, opcode, cycles);\n"
    elif (opcode_int & 0b11001111) == 9:
        main_block += f"            handle_add_hl_r16(gb, opcode, cycles);\n"
    elif (opcode_int & 0b11000111) == 6:
        main_block += f"            handle_ld_r8_imm8(gb, opcode, cycles);\n"
    elif (opcode_int & 0b11000111) == 7:
        main_block += f"            handle_flags_etc(gb, opcode, cycles);\n"
    elif (opcode_int) == 24:
        main_block += f"            handle_jr_imm8(gb, opcode, cycles);\n"
    elif (opcode_int & 0b11100111) == 32:
        main_block += f"            handle_jr_c_imm8(gb, opcode, cycles);\n"
    elif (opcode_int) == 16:
        main_block += f"            handle_stop(gb, opcode, cycles);\n"
    elif (opcode_int & 0b11000000) == 64:
        if opcode_int == 0x76:
            main_block += f"            handle_halt(gb, opcode, cycles);\n"
        else:
            main_block += f"            handle_ld_r8_r8(gb, opcode, cycles);\n"
    elif (opcode_int & 0b11000000) == 128:
        main_block += f"            handle_alu_r8(gb, opcode, cycles);\n"
    elif (opcode_int & 0b11000111) == 198:
        main_block += f"            handle_alu_imm8(gb, opcode, cycles);\n"
    elif (opcode_int & 0b11100111) == 192:
        main_block += f"            handle_ret_c(gb, opcode, cycles);\n"
    elif (opcode_int) == 201:
        main_block += f"            handle_ret(gb, opcode, cycles);\n"
    elif (opcode_int) == 217:
        main_block += f"            handle_reti(gb, opcode, cycles);\n"
    elif (opcode_int & 0b11100111) == 194:
        main_block += f"            handle_jp_c_imm16(gb, opcode, cycles);\n"
    elif (opcode_int) == 195:
        main_block += f"            handle_jp_imm16(gb, opcode, cycles);\n"
    elif (opcode_int) == 233:
        main_block += f"            handle_jp_hl(gb, opcode, cycles);\n"
    elif (opcode_int & 0b11100111) == 196:
        main_block += f"            handle_call_c_imm16(gb, opcode, cycles);\n"
    elif (opcode_int) == 205:
        main_block += f"            handle_call_imm16(gb, opcode, cycles);\n"
    elif (opcode_int & 0b11000111) == 199:
        main_block += f"            handle_rst(gb, opcode, cycles);\n"
    elif (opcode_int & 0b11001111) == 193:
        main_block += f"            handle_pop(gb, opcode, cycles);\n"
    elif (opcode_int & 0b11001111) == 197:
        main_block += f"            handle_push(gb, opcode, cycles);\n"
    elif (opcode_int) == 0xCB:
        main_block += f"            handle_prefix(gb, opcode, cycles);\n"
    elif (opcode_int) == 0xE2:
        main_block += f"            handle_ldh_c_a(gb, opcode, cycles);\n"
    elif (opcode_int) == 0xE0:
        main_block += f"            handle_ldh_imm8_a(gb, opcode, cycles);\n"
    elif (opcode_int) == 0xEA:
        main_block += f"            handle_ld_imm16_a(gb, opcode, cycles);\n"
    elif (opcode_int) == 0xF2:
        main_block += f"            handle_ldh_a_c(gb, opcode, cycles);\n"
    elif (opcode_int) == 0xF0:
        main_block += f"            handle_ldh_a_imm8(gb, opcode, cycles);\n"
    elif (opcode_int) == 0xFA:
        main_block += f"            handle_ld_a_imm16(gb, opcode, cycles);\n"
    elif (opcode_int) == 0xE8:
        main_block += f"            handle_add_sp_imm8(gb, opcode, cycles);\n"
    elif (opcode_int) == 0xF8:
        main_block += f"            handle_ld_hl_sp_imm8(gb, opcode, cycles);\n"
    elif (opcode_int) == 0xF9:
        main_block += f"            handle_ld_sp_hl(gb, opcode, cycles);\n"
    elif (opcode_int) == 0xF3:
        main_block += f"            handle_di(gb, opcode, cycles);\n"
    elif (opcode_int) == 0xFB:
        main_block += f"            handle_ei(gb, opcode, cycles);\n"
            
        
    
        
    main_block += f"            break;\n"

outs = TEMPLATE.format(datetime_str=datetime_string, main_block=main_block)

with open("core/boilerplate.c", "w") as outf:
    outf.write(outs)