/*
 * C DMG Gameboy Emulator Project - MorganPG
 * 
 * core/boilerplate.c
 * 
 * An autogenerated boilerplate generated by gen_boilerplate.py at 10/08/26 11:44:36
 * Do not edit this file manually, edit the generator
*/

#include <stdint.h>
#include <stdio.h>
#include "gb.h"
#include "cpu.h"

void execute_instr(dmg_gameboy_t *gb, uint8_t opcode) {
    uint8_t cycles[] = {0,0};
    switch (opcode) {
        case 0x00: // NOP
            cycles[0] = 0;
            break;
        case 0x01: // LD BC, n16
            cycles[0] = 8;
            handle_ld_r16_imm16(gb, opcode, cycles);
            break;
        case 0x02: // LD [BC], A
            cycles[0] = 4;
            handle_ld_r16mem_a(gb, opcode, cycles);
            break;
        case 0x03: // INC BC
            cycles[0] = 4;
            handle_inc_r16(gb, opcode, cycles);
            break;
        case 0x04: // INC B
            cycles[0] = 0;
            break;
        case 0x05: // DEC B
            cycles[0] = 0;
            break;
        case 0x06: // LD B, n8
            cycles[0] = 4;
            handle_ld_r8_imm8(gb, opcode, cycles);
            break;
        case 0x07: // RLCA
            cycles[0] = 0;
            handle_flags_etc(gb, opcode, cycles);
            break;
        case 0x08: // LD [a16], SP
            cycles[0] = 16;
            handle_ld_imm16_sp(gb, opcode, cycles);
            break;
        case 0x09: // ADD HL, BC
            cycles[0] = 4;
            handle_add_hl_r16(gb, opcode, cycles);
            break;
        case 0x0A: // LD A, [BC]
            cycles[0] = 4;
            handle_ld_a_r16mem(gb, opcode, cycles);
            break;
        case 0x0B: // DEC BC
            cycles[0] = 4;
            handle_dec_r16(gb, opcode, cycles);
            break;
        case 0x0C: // INC C
            cycles[0] = 0;
            break;
        case 0x0D: // DEC C
            cycles[0] = 0;
            break;
        case 0x0E: // LD C, n8
            cycles[0] = 4;
            handle_ld_r8_imm8(gb, opcode, cycles);
            break;
        case 0x0F: // RRCA
            cycles[0] = 0;
            handle_flags_etc(gb, opcode, cycles);
            break;
        case 0x10: // STOP n8
            cycles[0] = 0;
            handle_stop(gb, opcode, cycles);
            break;
        case 0x11: // LD DE, n16
            cycles[0] = 8;
            handle_ld_r16_imm16(gb, opcode, cycles);
            break;
        case 0x12: // LD [DE], A
            cycles[0] = 4;
            handle_ld_r16mem_a(gb, opcode, cycles);
            break;
        case 0x13: // INC DE
            cycles[0] = 4;
            handle_inc_r16(gb, opcode, cycles);
            break;
        case 0x14: // INC D
            cycles[0] = 0;
            break;
        case 0x15: // DEC D
            cycles[0] = 0;
            break;
        case 0x16: // LD D, n8
            cycles[0] = 4;
            handle_ld_r8_imm8(gb, opcode, cycles);
            break;
        case 0x17: // RLA
            cycles[0] = 0;
            handle_flags_etc(gb, opcode, cycles);
            break;
        case 0x18: // JR e8
            cycles[0] = 8;
            handle_jr_imm8(gb, opcode, cycles);
            break;
        case 0x19: // ADD HL, DE
            cycles[0] = 4;
            handle_add_hl_r16(gb, opcode, cycles);
            break;
        case 0x1A: // LD A, [DE]
            cycles[0] = 4;
            handle_ld_a_r16mem(gb, opcode, cycles);
            break;
        case 0x1B: // DEC DE
            cycles[0] = 4;
            handle_dec_r16(gb, opcode, cycles);
            break;
        case 0x1C: // INC E
            cycles[0] = 0;
            break;
        case 0x1D: // DEC E
            cycles[0] = 0;
            break;
        case 0x1E: // LD E, n8
            cycles[0] = 4;
            handle_ld_r8_imm8(gb, opcode, cycles);
            break;
        case 0x1F: // RRA
            cycles[0] = 0;
            handle_flags_etc(gb, opcode, cycles);
            break;
        case 0x20: // JR NZ, e8
            cycles[0] = 8;
            cycles[1] = 4;
            handle_jr_c_imm8(gb, opcode, cycles);
            break;
        case 0x21: // LD HL, n16
            cycles[0] = 8;
            handle_ld_r16_imm16(gb, opcode, cycles);
            break;
        case 0x22: // LD [HL+], A
            cycles[0] = 4;
            handle_ld_r16mem_a(gb, opcode, cycles);
            break;
        case 0x23: // INC HL
            cycles[0] = 4;
            handle_inc_r16(gb, opcode, cycles);
            break;
        case 0x24: // INC H
            cycles[0] = 0;
            break;
        case 0x25: // DEC H
            cycles[0] = 0;
            break;
        case 0x26: // LD H, n8
            cycles[0] = 4;
            handle_ld_r8_imm8(gb, opcode, cycles);
            break;
        case 0x27: // DAA
            cycles[0] = 0;
            handle_flags_etc(gb, opcode, cycles);
            break;
        case 0x28: // JR Z, e8
            cycles[0] = 8;
            cycles[1] = 4;
            handle_jr_c_imm8(gb, opcode, cycles);
            break;
        case 0x29: // ADD HL, HL
            cycles[0] = 4;
            handle_add_hl_r16(gb, opcode, cycles);
            break;
        case 0x2A: // LD A, [HL+]
            cycles[0] = 4;
            handle_ld_a_r16mem(gb, opcode, cycles);
            break;
        case 0x2B: // DEC HL
            cycles[0] = 4;
            handle_dec_r16(gb, opcode, cycles);
            break;
        case 0x2C: // INC L
            cycles[0] = 0;
            break;
        case 0x2D: // DEC L
            cycles[0] = 0;
            break;
        case 0x2E: // LD L, n8
            cycles[0] = 4;
            handle_ld_r8_imm8(gb, opcode, cycles);
            break;
        case 0x2F: // CPL
            cycles[0] = 0;
            handle_flags_etc(gb, opcode, cycles);
            break;
        case 0x30: // JR NC, e8
            cycles[0] = 8;
            cycles[1] = 4;
            handle_jr_c_imm8(gb, opcode, cycles);
            break;
        case 0x31: // LD SP, n16
            cycles[0] = 8;
            handle_ld_r16_imm16(gb, opcode, cycles);
            break;
        case 0x32: // LD [HL-], A
            cycles[0] = 4;
            handle_ld_r16mem_a(gb, opcode, cycles);
            break;
        case 0x33: // INC SP
            cycles[0] = 4;
            handle_inc_r16(gb, opcode, cycles);
            break;
        case 0x34: // INC [HL]
            cycles[0] = 8;
            break;
        case 0x35: // DEC [HL]
            cycles[0] = 8;
            break;
        case 0x36: // LD [HL], n8
            cycles[0] = 8;
            handle_ld_r8_imm8(gb, opcode, cycles);
            break;
        case 0x37: // SCF
            cycles[0] = 0;
            handle_flags_etc(gb, opcode, cycles);
            break;
        case 0x38: // JR C, e8
            cycles[0] = 8;
            cycles[1] = 4;
            handle_jr_c_imm8(gb, opcode, cycles);
            break;
        case 0x39: // ADD HL, SP
            cycles[0] = 4;
            handle_add_hl_r16(gb, opcode, cycles);
            break;
        case 0x3A: // LD A, [HL-]
            cycles[0] = 4;
            handle_ld_a_r16mem(gb, opcode, cycles);
            break;
        case 0x3B: // DEC SP
            cycles[0] = 4;
            handle_dec_r16(gb, opcode, cycles);
            break;
        case 0x3C: // INC A
            cycles[0] = 0;
            break;
        case 0x3D: // DEC A
            cycles[0] = 0;
            break;
        case 0x3E: // LD A, n8
            cycles[0] = 4;
            handle_ld_r8_imm8(gb, opcode, cycles);
            break;
        case 0x3F: // CCF
            cycles[0] = 0;
            handle_flags_etc(gb, opcode, cycles);
            break;
        case 0x40: // LD B, B
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x41: // LD B, C
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x42: // LD B, D
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x43: // LD B, E
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x44: // LD B, H
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x45: // LD B, L
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x46: // LD B, [HL]
            cycles[0] = 4;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x47: // LD B, A
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x48: // LD C, B
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x49: // LD C, C
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x4A: // LD C, D
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x4B: // LD C, E
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x4C: // LD C, H
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x4D: // LD C, L
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x4E: // LD C, [HL]
            cycles[0] = 4;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x4F: // LD C, A
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x50: // LD D, B
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x51: // LD D, C
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x52: // LD D, D
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x53: // LD D, E
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x54: // LD D, H
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x55: // LD D, L
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x56: // LD D, [HL]
            cycles[0] = 4;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x57: // LD D, A
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x58: // LD E, B
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x59: // LD E, C
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x5A: // LD E, D
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x5B: // LD E, E
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x5C: // LD E, H
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x5D: // LD E, L
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x5E: // LD E, [HL]
            cycles[0] = 4;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x5F: // LD E, A
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x60: // LD H, B
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x61: // LD H, C
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x62: // LD H, D
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x63: // LD H, E
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x64: // LD H, H
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x65: // LD H, L
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x66: // LD H, [HL]
            cycles[0] = 4;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x67: // LD H, A
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x68: // LD L, B
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x69: // LD L, C
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x6A: // LD L, D
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x6B: // LD L, E
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x6C: // LD L, H
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x6D: // LD L, L
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x6E: // LD L, [HL]
            cycles[0] = 4;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x6F: // LD L, A
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x70: // LD [HL], B
            cycles[0] = 4;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x71: // LD [HL], C
            cycles[0] = 4;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x72: // LD [HL], D
            cycles[0] = 4;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x73: // LD [HL], E
            cycles[0] = 4;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x74: // LD [HL], H
            cycles[0] = 4;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x75: // LD [HL], L
            cycles[0] = 4;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x76: // HALT
            cycles[0] = 0;
            handle_halt(gb, opcode, cycles);
            break;
        case 0x77: // LD [HL], A
            cycles[0] = 4;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x78: // LD A, B
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x79: // LD A, C
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x7A: // LD A, D
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x7B: // LD A, E
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x7C: // LD A, H
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x7D: // LD A, L
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x7E: // LD A, [HL]
            cycles[0] = 4;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x7F: // LD A, A
            cycles[0] = 0;
            handle_ld_r8_r8(gb, opcode, cycles);
            break;
        case 0x80: // ADD A, B
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x81: // ADD A, C
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x82: // ADD A, D
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x83: // ADD A, E
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x84: // ADD A, H
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x85: // ADD A, L
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x86: // ADD A, [HL]
            cycles[0] = 4;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x87: // ADD A, A
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x88: // ADC A, B
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x89: // ADC A, C
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x8A: // ADC A, D
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x8B: // ADC A, E
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x8C: // ADC A, H
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x8D: // ADC A, L
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x8E: // ADC A, [HL]
            cycles[0] = 4;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x8F: // ADC A, A
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x90: // SUB A, B
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x91: // SUB A, C
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x92: // SUB A, D
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x93: // SUB A, E
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x94: // SUB A, H
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x95: // SUB A, L
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x96: // SUB A, [HL]
            cycles[0] = 4;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x97: // SUB A, A
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x98: // SBC A, B
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x99: // SBC A, C
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x9A: // SBC A, D
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x9B: // SBC A, E
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x9C: // SBC A, H
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x9D: // SBC A, L
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x9E: // SBC A, [HL]
            cycles[0] = 4;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0x9F: // SBC A, A
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xA0: // AND A, B
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xA1: // AND A, C
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xA2: // AND A, D
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xA3: // AND A, E
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xA4: // AND A, H
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xA5: // AND A, L
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xA6: // AND A, [HL]
            cycles[0] = 4;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xA7: // AND A, A
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xA8: // XOR A, B
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xA9: // XOR A, C
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xAA: // XOR A, D
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xAB: // XOR A, E
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xAC: // XOR A, H
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xAD: // XOR A, L
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xAE: // XOR A, [HL]
            cycles[0] = 4;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xAF: // XOR A, A
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xB0: // OR A, B
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xB1: // OR A, C
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xB2: // OR A, D
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xB3: // OR A, E
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xB4: // OR A, H
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xB5: // OR A, L
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xB6: // OR A, [HL]
            cycles[0] = 4;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xB7: // OR A, A
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xB8: // CP A, B
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xB9: // CP A, C
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xBA: // CP A, D
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xBB: // CP A, E
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xBC: // CP A, H
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xBD: // CP A, L
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xBE: // CP A, [HL]
            cycles[0] = 4;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xBF: // CP A, A
            cycles[0] = 0;
            handle_alu_r8(gb, opcode, cycles);
            break;
        case 0xC0: // RET NZ
            cycles[0] = 16;
            cycles[1] = 4;
            handle_ret_c(gb, opcode, cycles);
            break;
        case 0xC1: // POP BC
            cycles[0] = 8;
            handle_pop(gb, opcode, cycles);
            break;
        case 0xC2: // JP NZ, a16
            cycles[0] = 12;
            cycles[1] = 8;
            handle_jp_c_imm16(gb, opcode, cycles);
            break;
        case 0xC3: // JP a16
            cycles[0] = 12;
            handle_jp_imm16(gb, opcode, cycles);
            break;
        case 0xC4: // CALL NZ, a16
            cycles[0] = 20;
            cycles[1] = 8;
            handle_call_c_imm16(gb, opcode, cycles);
            break;
        case 0xC5: // PUSH BC
            cycles[0] = 12;
            handle_push(gb, opcode, cycles);
            break;
        case 0xC6: // ADD A, n8
            cycles[0] = 4;
            handle_alu_imm8(gb, opcode, cycles);
            break;
        case 0xC7: // RST $00
            cycles[0] = 12;
            handle_rst(gb, opcode, cycles);
            break;
        case 0xC8: // RET Z
            cycles[0] = 16;
            cycles[1] = 4;
            handle_ret_c(gb, opcode, cycles);
            break;
        case 0xC9: // RET
            cycles[0] = 12;
            handle_ret(gb, opcode, cycles);
            break;
        case 0xCA: // JP Z, a16
            cycles[0] = 12;
            cycles[1] = 8;
            handle_jp_c_imm16(gb, opcode, cycles);
            break;
        case 0xCB: // PREFIX
            cycles[0] = 0;
            handle_prefix(gb, opcode, cycles);
            break;
        case 0xCC: // CALL Z, a16
            cycles[0] = 20;
            cycles[1] = 8;
            handle_call_c_imm16(gb, opcode, cycles);
            break;
        case 0xCD: // CALL a16
            cycles[0] = 20;
            handle_call_imm16(gb, opcode, cycles);
            break;
        case 0xCE: // ADC A, n8
            cycles[0] = 4;
            handle_alu_imm8(gb, opcode, cycles);
            break;
        case 0xCF: // RST $08
            cycles[0] = 12;
            handle_rst(gb, opcode, cycles);
            break;
        case 0xD0: // RET NC
            cycles[0] = 16;
            cycles[1] = 4;
            handle_ret_c(gb, opcode, cycles);
            break;
        case 0xD1: // POP DE
            cycles[0] = 8;
            handle_pop(gb, opcode, cycles);
            break;
        case 0xD2: // JP NC, a16
            cycles[0] = 12;
            cycles[1] = 8;
            handle_jp_c_imm16(gb, opcode, cycles);
            break;
        case 0xD3: // ILLEGAL_D3
            cycles[0] = 0;
            printf("Invalid opcode %02X", opcode);
            gb->running = false;
            break;
        case 0xD4: // CALL NC, a16
            cycles[0] = 20;
            cycles[1] = 8;
            handle_call_c_imm16(gb, opcode, cycles);
            break;
        case 0xD5: // PUSH DE
            cycles[0] = 12;
            handle_push(gb, opcode, cycles);
            break;
        case 0xD6: // SUB A, n8
            cycles[0] = 4;
            handle_alu_imm8(gb, opcode, cycles);
            break;
        case 0xD7: // RST $10
            cycles[0] = 12;
            handle_rst(gb, opcode, cycles);
            break;
        case 0xD8: // RET C
            cycles[0] = 16;
            cycles[1] = 4;
            handle_ret_c(gb, opcode, cycles);
            break;
        case 0xD9: // RETI
            cycles[0] = 12;
            handle_reti(gb, opcode, cycles);
            break;
        case 0xDA: // JP C, a16
            cycles[0] = 12;
            cycles[1] = 8;
            handle_jp_c_imm16(gb, opcode, cycles);
            break;
        case 0xDB: // ILLEGAL_DB
            cycles[0] = 0;
            printf("Invalid opcode %02X", opcode);
            gb->running = false;
            break;
        case 0xDC: // CALL C, a16
            cycles[0] = 20;
            cycles[1] = 8;
            handle_call_c_imm16(gb, opcode, cycles);
            break;
        case 0xDD: // ILLEGAL_DD
            cycles[0] = 0;
            printf("Invalid opcode %02X", opcode);
            gb->running = false;
            break;
        case 0xDE: // SBC A, n8
            cycles[0] = 4;
            handle_alu_imm8(gb, opcode, cycles);
            break;
        case 0xDF: // RST $18
            cycles[0] = 12;
            handle_rst(gb, opcode, cycles);
            break;
        case 0xE0: // LDH [a8], A
            cycles[0] = 8;
            handle_ldh_imm8_a(gb, opcode, cycles);
            break;
        case 0xE1: // POP HL
            cycles[0] = 8;
            handle_pop(gb, opcode, cycles);
            break;
        case 0xE2: // LDH [C], A
            cycles[0] = 4;
            handle_ldh_c_a(gb, opcode, cycles);
            break;
        case 0xE3: // ILLEGAL_E3
            cycles[0] = 0;
            printf("Invalid opcode %02X", opcode);
            gb->running = false;
            break;
        case 0xE4: // ILLEGAL_E4
            cycles[0] = 0;
            printf("Invalid opcode %02X", opcode);
            gb->running = false;
            break;
        case 0xE5: // PUSH HL
            cycles[0] = 12;
            handle_push(gb, opcode, cycles);
            break;
        case 0xE6: // AND A, n8
            cycles[0] = 4;
            handle_alu_imm8(gb, opcode, cycles);
            break;
        case 0xE7: // RST $20
            cycles[0] = 12;
            handle_rst(gb, opcode, cycles);
            break;
        case 0xE8: // ADD SP, e8
            cycles[0] = 12;
            handle_add_sp_imm8(gb, opcode, cycles);
            break;
        case 0xE9: // JP HL
            cycles[0] = 0;
            handle_jp_hl(gb, opcode, cycles);
            break;
        case 0xEA: // LD [a16], A
            cycles[0] = 12;
            handle_ld_imm16_a(gb, opcode, cycles);
            break;
        case 0xEB: // ILLEGAL_EB
            cycles[0] = 0;
            printf("Invalid opcode %02X", opcode);
            gb->running = false;
            break;
        case 0xEC: // ILLEGAL_EC
            cycles[0] = 0;
            printf("Invalid opcode %02X", opcode);
            gb->running = false;
            break;
        case 0xED: // ILLEGAL_ED
            cycles[0] = 0;
            printf("Invalid opcode %02X", opcode);
            gb->running = false;
            break;
        case 0xEE: // XOR A, n8
            cycles[0] = 4;
            handle_alu_imm8(gb, opcode, cycles);
            break;
        case 0xEF: // RST $28
            cycles[0] = 12;
            handle_rst(gb, opcode, cycles);
            break;
        case 0xF0: // LDH A, [a8]
            cycles[0] = 8;
            handle_ldh_a_imm8(gb, opcode, cycles);
            break;
        case 0xF1: // POP AF
            cycles[0] = 8;
            handle_pop(gb, opcode, cycles);
            break;
        case 0xF2: // LDH A, [C]
            cycles[0] = 4;
            handle_ldh_a_c(gb, opcode, cycles);
            break;
        case 0xF3: // DI
            cycles[0] = 0;
            handle_di(gb, opcode, cycles);
            break;
        case 0xF4: // ILLEGAL_F4
            cycles[0] = 0;
            printf("Invalid opcode %02X", opcode);
            gb->running = false;
            break;
        case 0xF5: // PUSH AF
            cycles[0] = 12;
            handle_push(gb, opcode, cycles);
            break;
        case 0xF6: // OR A, n8
            cycles[0] = 4;
            handle_alu_imm8(gb, opcode, cycles);
            break;
        case 0xF7: // RST $30
            cycles[0] = 12;
            handle_rst(gb, opcode, cycles);
            break;
        case 0xF8: // LD HL, SP+, e8
            cycles[0] = 8;
            handle_ld_hl_sp_imm8(gb, opcode, cycles);
            break;
        case 0xF9: // LD SP, HL
            cycles[0] = 4;
            handle_ld_sp_hl(gb, opcode, cycles);
            break;
        case 0xFA: // LD A, [a16]
            cycles[0] = 12;
            handle_ld_a_imm16(gb, opcode, cycles);
            break;
        case 0xFB: // EI
            cycles[0] = 0;
            handle_ei(gb, opcode, cycles);
            break;
        case 0xFC: // ILLEGAL_FC
            cycles[0] = 0;
            printf("Invalid opcode %02X", opcode);
            gb->running = false;
            break;
        case 0xFD: // ILLEGAL_FD
            cycles[0] = 0;
            printf("Invalid opcode %02X", opcode);
            gb->running = false;
            break;
        case 0xFE: // CP A, n8
            cycles[0] = 4;
            handle_alu_imm8(gb, opcode, cycles);
            break;
        case 0xFF: // RST $38
            cycles[0] = 12;
            handle_rst(gb, opcode, cycles);
            break;

    }
}
